export const CHAT_CALL_BOX_COMPACTED = "CHAT_CALL_BOX_COMPACTED";
export const CHAT_CALL_BOX_NORMAL = "CHAT_CALL_BOX_NORMAL";
export const CHAT_CALL_STATUS_OUTGOING = "CHAT_CALL_STATUS_OUTGOING";
export const CHAT_CALL_STATUS_INCOMING = "CHAT_CALL_STATUS_INCOMING";
export const CHAT_CALL_STATUS_REJECTED = "CHAT_CALL_STATUS_REJECTED";
export const CHAT_CALL_STATUS_STARTED = "CHAT_CALL_STATUS_STARTED";
export const CHAT_CALL_STATUS_CONNECTION_LOST = "CHAT_CALL_STATUS_CONNECTION_LOST";
export const DROPPING_OUTGOING_TIME_OUT = 20000;
export const DROPPING_INCOMING_TIME_OUT = 21000;

